In [34]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


df = pd.read_csv("samples_geocoded.csv")

null_counts = df.isnull().sum()

In [35]:
df

,DOI,Sample_ID,Subsample_ID,Location,Countries,Source,Concentration,Concentration_Units,Color_Transparent,Color_Blue,...,Size_1.5_5um,Size_less_than_1.5um,Size_1_100um,Size_1_50um,Size_1_10um,Size_1_5um,Size_110_124nm,Size_0_20um,Approximate_Latitude,Approximate_Longitude
0,10.1016/j.watres.2017.11.011,1|10.1016/j.watres.2017.11.011,NaN,Germany,Germany,bottled water,14,particles/L,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.163818,10.447831
1,10.1016/j.watres.2017.11.011,2|10.1016/j.watres.2017.11.011,NaN,Germany,Germany,bottled water,118,particles/L,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.163818,10.447831
2,10.1016/j.watres.2017.11.011,3|10.1016/j.watres.2017.11.011,NaN,Germany,Germany,bottled water,50,particles/L,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.163818,10.447831
3,10.1016/j.watres.2017.11.011,4|10.1016/j.watres.2017.11.011,NaN,Germany,Germany,bottled water,11,particles/L,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.163818,10.447831
4,10.1039/c6ay01184e,1|10.1039/c6ay01184e,NaN,Germany,Germany,bottled water,19-Oct,particles/0.33 L,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Present,NaN,NaN,51.163818,10.447831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,10.1016/j.scitotenv.2021.148001,Spr|10.1016/j.scitotenv.2021.148001,NaN,"South-to-North Water Diversion Project, China",China,tap water,390,particles/m3,0.1447,0.1528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000074,104.999927
603,10.1016/j.scitotenv.2021.148001,Sum|10.1016/j.scitotenv.2021.148001,NaN,"South-to-North Water Diversion Project, China",China,tap water,360,particles/m3,0.1447,0.1528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000074,104.999927
604,10.1016/j.scitotenv.2021.148001,Aut|10.1016/j.scitotenv.2021.148001,NaN,"South-to-North Water Diversion Project, China",China,tap water,750,particles/m3,0.1447,0.1528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000074,104.999927
605,10.1016/j.scitotenv.2021.148001,Win|10.1016/j.scitotenv.2021.148001,NaN,"South-to-North Water Diversion Project, China",China,tap water,540,particles/m3,0.1447,0.1528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.000074,104.999927
606,10.1016/j.scitotenv.2022.154015,1|10.1016/j.scitotenv.2022.154015,NaN,South Korea,South Korea,tap water,0.2,particles/L,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.638392,127.696119

In [36]:
null_counts = df.isna().sum()/df.shape[0]
for n in null_counts:
    print(n)

0.0
0.0
0.7792421746293245
0.24546952224052718
0.24546952224052718
0.0
0.009884678747940691
0.009884678747940691
0.9752883031301482
0.9719934102141681
0.9752883031301482
1.0
1.0
1.0
0.9686985172981878
0.9934102141680395
0.9983525535420099
0.9769357495881383
0.9769357495881383
0.929159802306425
0.7397034596375618
0.7545304777594728
0.8517298187808896
0.9967051070840197
0.828665568369028
0.9176276771004942
0.9176276771004942
0.9901153212520593
0.9901153212520593
0.800658978583196
0.9950576606260296
0.9950576606260296
0.9835255354200988
0.9934102141680395
0.9901153212520593
0.9967051070840197
0.9917627677100495
0.9769357495881383
0.9884678747940692
0.8649093904448105
0.9983525535420099
0.9917627677100495
0.9373970345963756
0.9357495881383855
0.9983525535420099
0.9917627677100495
0.9983525535420099
0.9983525535420099
0.9983525535420099
0.9983525535420099
0.9868204283360791
0.9934102141680395
0.9983525535420099
0.9983525535420099
0.9983525535420099
0.9983525535420099
0.9983525535420099
0.9917627677100495
0.9967051070840197
0.9950576606260296
0.9917627677100495
0.9950576606260296
0.9983525535420099
0.9983525535420099
0.9967051070840197
0.9983525535420099
0.9983525535420099
0.7792421746293245
0.7677100494233937
0.929159802306425
0.9406919275123559
0.9308072487644151
0.9489291598023064
0.9983525535420099
0.9983525535420099
0.9752883031301482
0.9983525535420099
1.0
1.0
0.9769357495881383
0.9868204283360791
0.9769357495881383
0.9472817133443163
0.9769357495881383
1.0
0.9934102141680395
0.9934102141680395
0.9505766062602965
0.9769357495881383
0.9983525535420099
0.9769357495881383
1.0
0.9934102141680395
0.9967051070840197
0.9983525535420099
0.9324546952224053
0.9917627677100495
0.9719934102141681
0.9934102141680395
0.9258649093904449
0.9967051070840197
0.9917627677100495
1.0
0.9011532125205931
0.9983525535420099
0.9950576606260296
0.9950576606260296
0.9967051070840197
0.9950576606260296
0.9835255354200988
0.9835255354200988
1.0
0.9983525535420099
0.2553542009884679
0.2553542009884679

In [37]:
df.shape

(607, 115)

In [38]:
micro_df = pd.read_csv("Merged_Microplastic_Data.csv")
micro_df.isna().sum()/micro_df.shape[0]

Unnamed: 0                              0.000000
DOI                                     0.000000
Sample_ID                               0.000000
Location                                0.245470
Countries                               0.245470
Source                                  0.000000
Concentration                           0.009885
Concentration_Units                     0.009885
Approximate_Latitude                    0.255354
Approximate_Longitude                   0.255354
Sample_device_and_deployment_methods    0.034596
Digestion                               0.034596
Filtration                              0.034596
Filter_Size                             0.034596
Microplastic_Identification_Method      0.034596
Spectral_Analysis                       0.034596
Controls                                0.034596
dtype: float64

In [39]:
micro_df.shape

(607, 17)

In [40]:
micro_df[["Location", "Countries", "Source"]]

                                          Location    Countries         Source
0                                          Germany      Germany  bottled water
1                                          Germany      Germany  bottled water
2                                          Germany      Germany  bottled water
3                                          Germany      Germany  bottled water
4                                          Germany      Germany  bottled water
..                                             ...          ...            ...
602  South-to-North Water Diversion Project, China        China      tap water
603  South-to-North Water Diversion Project, China        China      tap water
604  South-to-North Water Diversion Project, China        China      tap water
605  South-to-North Water Diversion Project, China        China      tap water
606                                    South Korea  South Korea      tap water

[607 rows x 3 columns]

In [41]:
len(micro_df["Countries"].unique())

42

In [42]:
micro_df[micro_df["Countries"] == "USA"].shape

(34, 17)

In [43]:
micro_df.columns

Index(['Unnamed: 0', 'DOI', 'Sample_ID', 'Location', 'Countries', 'Source',
       'Concentration', 'Concentration_Units', 'Approximate_Latitude',
       'Approximate_Longitude', 'Sample_device_and_deployment_methods',
       'Digestion', 'Filtration', 'Filter_Size',
       'Microplastic_Identification_Method', 'Spectral_Analysis', 'Controls'],
      dtype='object')

In [44]:
micro_df.dtypes

Unnamed: 0                                int64
DOI                                      object
Sample_ID                                object
Location                                 object
Countries                                object
Source                                   object
Concentration                            object
Concentration_Units                      object
Approximate_Latitude                    float64
Approximate_Longitude                   float64
Sample_device_and_deployment_methods     object
Digestion                                object
Filtration                               object
Filter_Size                              object
Microplastic_Identification_Method       object
Spectral_Analysis                        object
Controls                                 object
dtype: object

In [45]:
micro_df.drop(["Unnamed: 0", "Approximate_Latitude", "Approximate_Longitude"], axis = 1)

,DOI,Sample_ID,Location,Countries,Source,Concentration,Concentration_Units,Sample_device_and_deployment_methods,Digestion,Filtration,Filter_Size,Microplastic_Identification_Method,Spectral_Analysis,Controls
0,10.1016/j.watres.2017.11.011,1|10.1016/j.watres.2017.11.011,Germany,Germany,bottled water,14,particles/L,Pre packaged bevarage cartons,Not Provided,polycarbonate filter,3 um,"Single Particle Explorer (SPE, rapID, Berlin)",Raman,Blank filters run through Raman
1,10.1016/j.watres.2017.11.011,2|10.1016/j.watres.2017.11.011,Germany,Germany,bottled water,118,particles/L,Pre packaged bevarage cartons,Not Provided,polycarbonate filter,3 um,"Single Particle Explorer (SPE, rapID, Berlin)",Raman,Blank filters run through Raman
2,10.1016/j.watres.2017.11.011,3|10.1016/j.watres.2017.11.011,Germany,Germany,bottled water,50,particles/L,Pre packaged bevarage cartons,Not Provided,polycarbonate filter,3 um,"Single Particle Explorer (SPE, rapID, Berlin)",Raman,Blank filters run through Raman
3,10.1016/j.watres.2017.11.011,4|10.1016/j.watres.2017.11.011,Germany,Germany,bottled water,11,particles/L,Pre packaged bevarage cartons,Not Provided,polycarbonate filter,3 um,"Single Particle Explorer (SPE, rapID, Berlin)",Raman,Blank filters run through Raman
4,10.1039/c6ay01184e,1|10.1039/c6ay01184e,Germany,Germany,bottled water,19-Oct,particles/0.33 L,Pre packaged bevarage cartons,Not Provided,Cellulose nitrate,0.45 um,Raman scattering spectroscopy,Raman,Already analyzes sample filtered a second time...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,10.1016/j.scitotenv.2021.148001,Spr|10.1016/j.scitotenv.2021.148001,"South-to-North Water Diversion Project, China",China,tap water,390,particles/m3,Drinking water canal,H2O2,Glass fiber,Not Provided,Not Provided,Not Provided,Plastic equiptment minimized
603,10.1016/j.scitotenv.2021.148001,Sum|10.1016/j.scitotenv.2021.148001,"South-to-North Water Diversion Project, China",China,tap water,360,particles/m3,Drinking water canal,H2O2,Glass fiber,Not Provided,Not Provided,Not Provided,Plastic equiptment minimized
604,10.1016/j.scitotenv.2021.148001,Aut|10.1016/j.scitotenv.2021.148001,"South-to-North Water Diversion Project, China",China,tap water,750,particles/m3,Drinking water canal,H2O2,Glass fiber,Not Provided,Not Provided,Not Provided,Plastic equiptment minimized
605,10.1016/j.scitotenv.2021.148001,Win|10.1016/j.scitotenv.2021.148001,"South-to-North Water Diversion Project, China",China,tap water,540,particles/m3,Drinking water canal,H2O2,Glass fiber,Not Provided,Not Provided,Not Provided,Plastic equiptment minimized
606,10.1016/j.scitotenv.2022.154015,1|10.1016/j.scitotenv.2022.154015,South Korea,South Korea,tap water,0.2,particles/L,Drinking water from treatment facilities,H2O2,Al2O3,0.2 um,micro FTIR,FTIR,Procedural blanks; plastic equiptment minimized

### Concentration
Has an error

### Filter Size
Replace "Not Provided" with numpy.  Get rid of micrometer measurement

In [55]:
micro_df[micro_df["Concentration"] == "19-Oct"]

,Unnamed: 0,DOI,Sample_ID,Location,Countries,Source,Concentration,Concentration_Units,Approximate_Latitude,Approximate_Longitude,Sample_device_and_deployment_methods,Digestion,Filtration,Filter_Size,Microplastic_Identification_Method,Spectral_Analysis,Controls
4,4,10.1039/c6ay01184e,1|10.1039/c6ay01184e,Germany,Germany,bottled water,19-Oct,particles/0.33 L,51.163818,10.447831,Pre packaged bevarage cartons,Not Provided,Cellulose nitrate,0.45 um,Raman scattering spectroscopy,Raman,Already analyzes sample filtered a second time...

In [ ]:
micro_df["Filter_Size"].replace("Not Provided", np.nan, inplace = True)
#find out how to

In [47]:
sns.scatterplot(x = , y = "Filtration", hue = "Countries" , df = micro_df)

SyntaxError: expected argument value expression (1145291901.py, line 1)